### ISSUE TITLE
Runs before block as well although the tests don't run

### ISSUE THREAD

**Issue by vkolgi** [bahmutov/cypress-grep#28]
One specific issue is that the before block runs for tests which are not supposed to run.

```
describe('My First Test', () => {

  it('Does not do much! @smoke', () => {
    expect(true).to.equal(true)
  })

  it("Does not do much either!, but shouldn't run", () => {
    expect(true).to.equal(true)
  })

})

describe('Tests with before block', () => {

  before('You know, setting up fixtures', () => {
    cy.visit('http://google.com')
    cy.log('setting up fixtures')
  })

  it('Tests with the before block', () => {
    expect(true).to.equal(true)
  })

  it("Tests with the before block, again", () => {
    expect(true).to.equal(true)
  })

})

```
Strangely the commands of the before block doesn't show up in the command log.
Here if I grep with @smoke the tests in second describe block won't run but the before block does. Is there any way to skip them as well ?

**Comment by bahmutov** [comment]
What happens if you set it to it.skip for all tests in the second block? Does it still run the before hook? It could be how mocha and cypress execute it

**Comment by vkolgi** [comment]
Not sure if there is a workaround for this, I want to take a stab at this. 
From the code it looks like it's harder to get some sort of look ahead, where skip before block if corresponding tests are not supposed to run.

**Comment by vkolgi** [comment]
@bahmutov I tried with the `it.skip` for all the tests in second block. It still runs the before hook.

**Comment by bahmutov** [comment]
So this is mocha problem. I think in this case one would need to explicitly skip the suite and use tags

**Comment by vkolgi** [comment]
Yeah since this is consistent with mocha, shall I close the issue ?

**Comment by bahmutov** [comment]
Yeah since this plug-in cannot really control this
