### ISSUE TITLE
cypress grep filtering test cases even when grepTags is not passed.

### ISSUE THREAD

**Issue by Ppkd2021** [bahmutov/cypress-grep#34]
1. `"test:cypress-ui-regression": "ng run convosight-web-client:cypress-run -- --record --key random --browser chrome --parallel --ci-build-id $BITBUCKET_BUILD_NUMBER --group ui-tests --spec 'cypress/tests/ui/**/*'"`,
2. `"test:cypress-ui-smoke": "ng run convosight-web-client:cypress-run -- --record --key Random-env grepTags=@pullRequest  --browser chrome --parallel --ci-build-id $BITBUCKET_BUILD_`

For both the command it's filtering the tests based on tag @pullRequest but we wanted to filter it only for the second npm command and not for the first. When we run the first command it should run all the test cases even with tag @pullrequest.

FYI, We have kept grepTags in cypress.json under env.

**Comment by bahmutov** [comment]
You mentioned that `grepTags` is present in your `cypress.json` - this is where the first run gets it from. From the point of the  plugin it does not matter where `grepTags is coming from. Remove it from the cypress.json and it should NOT filter.

**Comment by Ppkd2021** [comment]
@bahmutov If I remove it from cypress.json then it does not filter the tests for command 2 also.

**Comment by bahmutov** [comment]
I would suggest doing the opposite: 
- have all tests run by default
- pass grep tags from the command line when needed
See my example in https://www.youtube.com/watch?v=SFW7Ecj5TNE

**Comment by Ppkd2021** [comment]
@bahmutov Got it, Thanks for the information :)
