### ISSUE TITLE
 can we have this plugin for TypeScript

### ISSUE THREAD

**Issue by inmotionnowalex** [bahmutov/cypress-grep#35]
please need selected tests for typescript

**Comment by TheNiron** [comment]
@bahmutov can't we grep the test suites by **describe** block in TypeScript? I observed when I grepped all other tests' **`before`** and **`after`** blocks are getting executed still

**Comment by bahmutov** [comment]
@inmotionnowalex this plugin does not work for TypeScript?!

@TheNiron see https://github.com/bahmutov/cypress-grep#test-suites and https://github.com/bahmutov/cypress-grep/issues/28

**Comment by TheNiron** [comment]
@bahmutov Thanks for the reply. are the inverter tags for 'it' blocks working now? It worked for me. 😊 saw somewhere you have mentioned it's not implemented yet.

**Comment by bahmutov** [comment]
Yup, the `-tag` syntax should work everywhere, closing this issue as resolved
