### ISSUE TITLE
cypress-grep not filtering tests 

### ISSUE THREAD

**Issue by borecz** [bahmutov/cypress-grep#43]
Not sure when this stopped working but I've created a replica of my repo [here](https://github.com/borecz/cypress-various-tests) where you can check the implementation.

**Comment by bahmutov** [comment]
```
$ ts-node launch.ts --grepTags=-@flaky
Error: Cannot find module 'yargs/yargs'
Require stack:
- /Users/gleb/git/cypress-various-tests/launch.ts
```

**Comment by bahmutov** [comment]
<img width="572" alt="Screen Shot 2021-05-27 at 4 15 51 PM" src="https://user-images.githubusercontent.com/2212006/119891309-d0e04600-bf06-11eb-8ba0-6c97cfa5bbc7.png">

You are taking grep tags and putting them into `grep` field

```
env: {
    grep: GREP
  },
```

The title grep goes into `grep`, the tags go into `grepTags` (or `grep-tags`)

**Comment by bahmutov** [comment]
docs https://github.com/bahmutov/cypress-grep#use

kind of related: #41

**Comment by borecz** [comment]
my bad, thanks @bahmutov
